### PR TITLE
Support Laravel 11.x

### PR DESCRIPTION
**Pull request by SupianIDz**

### CODE REVIEW

**Review by lloricode — CHANGES_REQUESTED** [review]
Hi, please update also github workflow test with php8.3 and laravel 11, thank you

**Comment by shopauskunft-david** [comment]
+1 please merge; laravel 11 is releasing *today* :)

**Comment by UtkuDalmaz** [comment]
Can you please merge this?

**Comment by Saifallak** [comment]
@bezhanSalleh sorry for ping, but it's pretty simple PR if we can merge

**Comment by free-storage** [comment]
@bezhanSalleh @ThorgerSuenert @medeiroz @erjanmx @dev3k @ziming @mustafa-online @lukas-frey @tobiasla78
Make an update. My project development has stopped... I spent all day moving my project to version 11 and the only thing that created a problem was this plugin.

**Comment by Saifallak** [comment]
> @bezhanSalleh @ThorgerSuenert @medeiroz @erjanmx @dev3k @ziming @mustafa-online @lukas-frey @tobiasla78 Make an update. My project development has stopped... I spent all day moving my project to version 11 and the only thing that created a problem was this plugin.

If you need this update urgent, you can require this fork in composer. 

If you don't know how, i can show you

**Comment by Saifallak** [comment]
Screenshot_20240314_214854_Chrome

**Comment by lloricode** [comment]
+1

**Review by lloricode — APPROVED** [review]

**Comment by tsangaris** [comment]
Hi there,

Any idea when the official support for Laravel 11 will be out?

**Comment by bezhanSalleh** [comment]
Thanks. i will be closing this PR in favor of #86 to avoid future issues.

**Pull request closed without merging**
