### PR TITLE
Fixes Placement of dropdown in many scenarios

### LINKED ISSUE #90: outside panel placement always pointing to left side (top, bottom) only
This is my code inside `AppServiceProvider`
```php
public function boot(): void
{
    LanguageSwitch::configureUsing(function (LanguageSwitch $switch) {
        $switch
            ->locales(['en', 'zh_CN'])
            ->visible(outsidePanels: true)
            ->outsidePanelPlacement(Placement::TopCenter);
    });
}
```
And this is the result. No matter how I try to change the position, it always ended up to `TopLeft` or `BottomLeft` only

Screenshot from 2024-04-09 10-36-17

Laravel `v11.2.0`
Livewire `v3.4.10`
Filament `v3.2.63`
Language switch `v3.1.0`

### PR DESCRIPTION
**Pull request by kerwin-wildsea**
This PR fixes the dropdown menu misplacement in certain scenarios. 

---

# Includes:

- Using a different render hook which is present on profile pages (including `isSimple: true`
  - This also fixes a bug when using `$switch->outsidePanelRoutes()` with `$panel->profile(isSimple: false)` rendering the language switcher twice as both `isVisibleInsidePanels()` and `isVisibleOutsidePanels` return `true`
- It changes some styles to fix the 4 `(Top|Botom)(Center|Right)` `outsidePanelPlacement` options which all aligned `(Top|Bottom)Left`.
- Removal of `auth.profile` from default `outsidePanelRoutes()` function as the new render hook is used by both profile styles (simple and non-simple) handling profile as "outside" redundant.

---

- Fixes the same issue #91 attempted to fix as well
- Fixes #90 (Same as PR#91)

---

Style changes: 

```diff
// resources/dist/filament-language-switch.css
-.w-fit{width:-moz-fit-content;width:fit-content}
```

### CODE REVIEW

**Comment by kerwin-wildsea** [comment]
I've updated the description after removing most of the "ugly" logic for profile page checking. This seems like a great solution to the problem. If this was already evaluated, please do so again. Thanks 🙂

**Comment by kerwin-wildsea** [comment]
@bezhanSalleh A friendly reminder for this PR. If there's a reason this hasn't (or cannot) be merged, please let me know 🙂

**Comment by bezhanSalleh** [comment]
I thought i wrote back, my bad! So the reason this PR cannot be merged is, you can achieve the same result without it by just doing the following:
```php
LanguageSwitch::configureUsing(function (LanguageSwitch $switch) {
        $switch
            ...
            ->renderHook('panels::user-menu.before')
            ...;
    });
```
so i'm gonna close it. I'm currently swampped, though i did figure out how to make it work but that's gonna take awhile. maybe after the holidays.

**Comment by kerwin-wildsea** [comment]
> I thought i wrote back, my bad! 

@bezhanSalleh No worries ❤️
 
The solution you posted would indeed work. Hopefully it is something you'll eventually are able to get to, but for now it's nice that it can be achieved without hacky-ness! 

The other item this PR attempted to fix, was the broken alignment for `outsidePanelRoutes`. Which is exactly the same as #91. 
That can unfortunately not be fixed without using something like vendor patching. If you have some time in the future, maybe that could be merged (#91 is a lot less invasive compared to this PR). 

Either way, thanks for the quick response!

**Pull request closed without merging**
