### PR TITLE
issue-12 fixed registration component to work with laravel octane

### PR DESCRIPTION
**Pull request by medeiroz**
[issue-12](https://github.com/bezhanSalleh/filament-language-switch/issues/12)

### CODE REVIEW

**Comment by bezhanSalleh** [comment]
Thanks.

**Comment by bezhanSalleh** [comment]
fixes #12

**Comment by cobraprojects** [comment]
doesn't switch language
dongraded to v1.0.3 to get it work

**Comment by medeiroz** [comment]
> doesn't switch language downgraded to v1.0.3 to get it work

I created a new PR for solve this

**Pull request merged**
